#server:
#  port: 8110 # 服务端口
#  tomcat:
#    max-threads: 5 #Tomcat的最大并发值修改为10，默认200
##server:
##  tomcat:
##    uri-encoding: UTF-8
##    max-http-header-size: 8096
#
#spring:
#  profiles:
#    active: dev # 环境设置
#  application:
#    name: service-edu # 服务名
#  datasource: # mysql数据库连接
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: wan123
#  #spring:
#  jackson: #返回json的全局时间格式
#    date-format: yyyy-MM-dd
#    time-zone: GMT+8
#  #spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 #nacos服务地址
#
#  #将sentinel控制台添加进配置
##spring:
##  cloud:
#    sentinel:
#      transport:
#        port: 8081
#        dashboard: localhost:8080
#  redis:
#    host: 192.168.157.10
#    port: 6379
#    database: 0
#    password: #默认为空
#    lettuce:
#      pool:
#        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
##mybatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/project/guli/service/edu/mapper/xml/*.xml
#
## 设置日志级别
##logging:
##  level:
##    root: INFO
#
##service-oss: #调用的提供者的名称(服务的生产者） 因此在消费者端进行配置
##  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
## 当MaxAutoRetries为1，在该服务器上尝试2次，再在另一台服务器上尝试，为1时尝试两次，为2时，尝试两次后又切换到原服务器进行尝试两次
#ribbon:
#  MaxAutoRetries: 0 #同一实例最大重试次数，不包括首次调用，默认0
#  MaxAutoRetriesNextServer: 1 #重试其他实例的最大重试次数，不包括首次所选的server，默认1
#  ConnectTimeout: 50000 #连接建立的超时时长，默认1秒
#  ReadTimeout: 50000 #处理请求的超时时间，默认为1秒
#
##开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true
