server:
  port: 8150 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

  #spring:
  redis:
    host: 192.168.157.10
    port: 6379
    database: 0
    password: #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/project/guli/service/ucenter/mapper/xml/*.xml

aliyun:
  sms:
    regionId: cn-hangzhou
    keyId: LTAI4FymWD5ywEEcVC5NRKnY
    keySecret: i97K5ZF2bpsYNCm7TIk19HYYl1C1fy
    templateCode: SMS_198345058
    signName: 谷粒